Table
SQL
insert into product (ID, NAME, DESCRIPTION, VALUE) values (1, 'Chef Hat 20cm', '・(￣∀￣)・:*:', 57.07);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (2, 'Oil - Pumpkinseed', '"''''''''"''"', 30.19);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (3, 'Chilli Paste, Hot Sambal Oelek', 'åß∂ƒ©˙∆˚¬…æ', 51.97);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (4, 'Chocolate - Semi Sweet, Calets', '🐵 🙈 🙉 🙊', 83.77);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (5, 'Turkey Leg With Drum And Thigh', 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ', 42.91);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (6, 'Bread - French Baquette', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 83.97);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (7, 'Tortillas - Flour, 10', '1E+02', 85.77);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (8, 'Mushroom - White Button', 'œ∑´®†¥¨ˆøπ“‘', 83.29);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (9, 'Extract - Vanilla,artificial', '1;DROP TABLE users', 81.7);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (10, 'Chocolate - Semi Sweet', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 42.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (11, 'Fennel - Seeds', '-1.00', 66.17);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (12, 'Quail - Whole, Bone - In', '​', 53.9);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (13, 'Chinese Lemon Pork', '00˙Ɩ$-', 44.08);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (14, 'Irish Cream - Baileys', '00˙Ɩ$-', 55.79);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (15, 'Wine - Casillero Del Diablo', '''', 65.27);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (16, 'Wine - Chateau Timberlay', ' test ', 19.31);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (17, 'Pail - 4l White, With Handle', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 14.41);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (18, 'Turnip - White, Organic', '␢', 33.49);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (19, 'Chips Potato Swt Chilli Sour', '1''; DROP TABLE users--', 11.21);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (20, 'Soup - Campbells - Tomato', '"''"''"''''''''"', 55.9);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (21, 'Mushroom - Chanterelle, Dry', '田中さんにあげて下さい', 25.62);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (22, 'Ecolab - Hand Soap Form Antibac', '<img src=x onerror=alert(''hi'') />', 14.6);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (23, 'Wine - Red, Gamay Noir', '¸˛Ç◊ı˜Â¯˘¿', 86.03);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (24, 'Wine - Beaujolais Villages', '😍', 38.88);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (25, 'Pork - Sausage, Medium', '사회과학원 어학연구소', 75.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (26, 'Pork - Suckling Pig', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 38.8);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (27, 'Wine - White, French Cross', '0/0', 20.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (28, 'Water, Tap', '🐵 🙈 🙉 🙊', 84.12);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (29, 'Water - Aquafina Vitamin', '␢', 67.5);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (30, 'Beer - Pilsner Urquell', '<svg><script>0<1>alert(''XSS'')</script>', 16.69);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (31, 'Red Pepper Paste', '''', 11.74);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (32, 'Sauce - Bernaise, Mix', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 92.71);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (33, 'Nestea - Iced Tea', '(╯°□°）╯︵ ┻━┻)  ', 33.45);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (34, 'Kiwano', '🐵 🙈 🙉 🙊', 81.24);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (35, 'Flour - Whole Wheat', '1/0', 85.88);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (36, 'Tuna - Yellowfin', '田中さんにあげて下さい', 6.31);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (37, 'Cheese - Augre Des Champs', '0.00', 94.23);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (38, 'Cheese - Cambozola', 'Ω≈ç√∫˜µ≤≥÷', 23.77);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (39, 'Longos - Assorted Sandwich', '₀₁₂', 92.22);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (40, 'Sauce - Soya, Light', '​', 42.45);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (41, 'Wine - Saint Emilion Calvet', 'test⁠test‫', 23.8);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (42, 'Lamb - Whole Head Off', 'test⁠test‫', 99.96);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (43, 'Compound - Rum', '-1.00', 68.21);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (44, 'Chestnuts - Whole,canned', '<img src=x onerror=alert(''hi'') />', 19.5);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (45, 'Cheese - Gorgonzola', '¸˛Ç◊ı˜Â¯˘¿', 9.46);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (46, 'Hinge W Undercut', ' test ', 11.4);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (47, 'Sour Puss - Tangerine', '1', 25.33);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (48, 'Beef - Top Butt Aaa', '''', 92.19);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (49, 'Ice Cream - Strawberry', '😍', 21.36);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (50, 'Bread Foccacia Whole', '사회과학원 어학연구소', 25.73);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (51, 'Lychee - Canned', '`⁄€‹›ﬁﬂ‡°·‚—±', 51.53);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (52, 'Chocolate - Dark', '-1', 82.58);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (53, 'Prunes - Pitted', 'パーティーへ行かないか', 6.98);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (54, 'Oil - Olive Bertolli', '<svg><script>0<1>alert(''XSS'')</script>', 61.02);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (55, 'Arizona - Plum Green Tea', '1;DROP TABLE users', 81.98);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (56, 'Pasta - Lasagna Noodle, Frozen', '"', 87.77);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (57, 'Beef - Ox Tongue', '​', 38.99);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (58, 'Dill Weed - Dry', '₀₁₂', 61.22);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (59, 'Appetizer - Escargot Puff', '社會科學院語學研究所', 31.08);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (60, 'Wine - Red, Harrow Estates, Cab', '̦H̬̤̗̤͝e͜ ̜̥̝̻͍̟́w̕h̖̯͓o̝͙̖͎̱̮ ҉̺̙̞̟͈W̷̼̭a̺̪͍į͈͕̭͙̯̜t̶̼̮s̘͙͖̕ ̠̫̠B̻͍͙͉̳ͅe̵h̵̬͇̫͙i̹͓̳̳̮͎̫̕n͟d̴̪̜̖ ̰͉̩͇͙̲͞ͅT͖̼͓̪͢h͏͓̮̻e̬̝̟ͅ ̤̹̝W͙̞̝͔͇͝ͅa͏͓͔̹̼̣l̴͔̰̤̟͔ḽ̫.͕', 73.54);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (61, 'Sea Bass - Whole', '田中さんにあげて下さい', 89.91);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (62, 'Cheese - La Sauvagine', 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ', 93.3);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (63, 'Cheese - St. Paulin', '../../../../../../../../../../../etc/hosts', 20.32);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (64, 'Longos - Grilled Salmon With Bbq', '1/2', 14.57);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (65, 'Pork - European Side Bacon', '𠜎𠜱𠝹𠱓𠱸𠲖𠳏', 12.12);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (66, 'Lobster - Baby, Boiled', '0/0', 84.81);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (67, 'Tea - Honey Green Tea', 'nil', 32.77);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (68, 'Wine - Black Tower Qr', '⁰⁴⁵', 61.56);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (69, 'Poppy Seed', '１２３', 76.25);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (70, 'Nori Sea Weed', '1/0', 23.22);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (71, 'Cheese - Gouda', '-1', 53.12);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (72, 'Corn - Cream, Canned', ' ', 45.43);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (73, 'Chocolate Bar - Reese Pieces', 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮', 67.42);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (74, 'Bacardi Limon', '''''', 87.1);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (75, 'Chocolate Bar - Oh Henry', '​', 87.72);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (76, 'Muffin Batt - Carrot Spice', '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟', 78.71);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (77, 'Soap - Hand Soap', '<>?:"{}|_+', 85.84);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (78, 'Pineapple - Regular', ' ', 57.65);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (79, 'Wine - Cotes Du Rhone', '<script>alert(''hi'')</script>', 52.69);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (80, 'Oil - Shortening,liqud, Fry', '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻', 99.79);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (81, 'Limes', '1E2', 56.58);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (82, 'Orange - Canned, Mandarin', '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰', 34.16);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (83, 'Pepper - Red Chili', '¡™£¢∞§¶•ªº–≠', 65.21);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (84, 'Wine - Cahors Ac 2000, Clos', 'Œ„´‰ˇÁ¨ˆØ∏”’', 25.61);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (85, 'Vol Au Vents', '１２３', 95.51);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (86, 'Yogurt - Plain', '1E+02', 5.7);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (87, 'Wine - Puligny Montrachet A.', '¡™£¢∞§¶•ªº–≠', 96.6);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (88, 'Juice - Mango', 'ثم نفس سقطت وبالتحديد،, جزيرتي باستخدام أن دنو. إذ هنا؟ الستار وتنصيب كان. أهّل ايطاليا، بريطانيا-فرنسا قد أخذ. سليمان، إتفاقية بين ما, يذكر الحدود أي بعد, معاملة بولندا، الإطلاق عل إيو.', 3.23);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (89, 'Soup - Knorr, Chicken Gumbo', '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ', 17.37);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (90, 'Vermouth - White, Cinzano', '1E2', 78.91);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (91, 'Wine - Spumante Bambino White', 'ÅÍÎÏ˝ÓÔÒÚÆ☃', 2.48);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (92, 'Yogurt - Cherry, 175 Gr', 'Œ„´‰ˇÁ¨ˆØ∏”’', 95.68);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (93, 'Corn Syrup', 'NULL', 46.95);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (94, 'Salmon Steak - Cohoe 8 Oz', '田中さんにあげて下さい', 51.97);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (95, 'Veal - Slab Bacon', '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟', 3.6);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (96, 'Wine - White, Concha Y Toro', '$1.00', 50.45);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (97, 'Ecolab - Medallion', '・(￣∀￣)・:*:', 38.89);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (98, 'Onions - Dried, Chopped', 'åß∂ƒ©˙∆˚¬…æ', 70.56);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (99, 'Chilli Paste, Ginger Garlic', '田中さんにあげて下さい', 70.37);
insert into product (ID, NAME, DESCRIPTION, VALUE) values (100, 'Bag Clear 10 Lb', '(╯°□°）╯︵ ┻━┻)  ', 40.48);